sudo: required
services:
  - docker
before_install:
  - docker build -t afreda323/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run afreda323/react-test npm test -- --coverage
after_success:
  - docker build -t afreda323/multi-client ./client
  - docker build -t afreda323/multi-api ./api
  - docker build -t afreda323/multi-worker ./worker
  - docker build -t afreda323/multi-nginx ./nginx

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push afreda323/multi-client
  - docker push afreda323/multi-api
  - docker push afreda323/multi-worker
  - docker push afreda323/multi-nginx
deploy:
  provide: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-983895567626
  bucker_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY